name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Compile and test
        run: sbt test